---
title: "IODS course project"
author: "Yuwen Pang"
output:
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
    
---

***
```{r}
options(knitr.duplicate.label = "allow")
```

# Introduction to Open Data Science - Course Project

```{r child = "chapter1.Rmd"}
# This will include Chapter 1 (that is updated in its own file) in the document.
```
  
***
  
```{r child = "chapter2.Rmd"}
# This will include Chapter 2 (that is updated in its own file) in the document.
```

***

```{r child = "chapter3.Rmd"}
# This will include Chapter 3 (that is updated in its own file) in the document.
```

***
```{r child = "chapter4.Rmd"}
# This will include Chapter 4 (that is updated in its own file) in the document.
```

***
```{r child= "chapter5.Rmd"}
# This will include Chapter 5 (that is updated in its own file) in the document.
```

***
```{r child= "chapter6.Rmd"}
# This will include Chapter 6 (that is updated in its own file) in the document.
```
```
Congratulations! Now All chapters have been added!


